- name: 'Create env file'
        run: |
          touch .env
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" > .env
          echo API_KEY=${{ secrets.API_KEY }} > .env
          cat .env
    
